### PR TITLE
Check that download is eligible to be downloaded and other misc related issues

### PR DESCRIPTION
**Pull request by chriscct7**
Fixes:
Security 1: Download can be added to cart when the download is not published ( draft/trash/etc)

Security 2: Fixes email sanitation and validation

Security 3: Prevent variable prices from using modal

Bug 1: Download as bundle can be added to modal when Free Downloads doesn't support bundles.

Bug 2: Fixes lack of isset before nonce checking

Bug 3: Ensure download is download object before using it as an object 

Enhancement 1: Use more descriptive variable names

### CODE REVIEW

**Comment by chriscct7** [comment]
This should be tested. This pr has not been tested yet.

**Comment by pippinsplugins** [comment]
@ghost1227 Please test this extensively. At first glance the changes look good to me.

**Comment by ghost1227** [comment]
Testing

**Comment by ghost1227** [comment]
Fixed with https://github.com/easydigitaldownloads/edd-free-downloads/commit/b2efaacc213a5a6ebf2a6c02361c21ed81d3810d

**Pull request closed without merging**
