### PR TITLE
Remove dashicons and use HTML chars instead #268

### LINKED ISSUE #268: Remove dependancy of Dashicons from the front end.
As it stands, Dashicons is only loaded on the front end for the `X` to close the modal. We should be able to find a way around having to load the entire Dashicons just for this.

Since Admin loads dashicons anyway, we don't have to worry about dependencies there.

### PR DESCRIPTION
**Pull request by cklosowski**
Resolves #268

Proposed Changes:
1) Removes `dashicons` from being enqueued on the front end.
2) Switches `dashicons dashicons-no-alt` to using the `&#10005;` HTML character
3) Includes styles to properly center the `X` character

### CODE REVIEW

**Comment by samikeijonen** [comment]
+100000000

**Comment by cklosowski** [comment]
@samikeijonen Looking at this change, is there anything I should be doing from an accessibility perspective to make this (staying in the scope of the changes) to make it more accessible?

**Comment by SDavisMedia** [comment]
I made some tweaks.

1. Reduced the wrapping `<span>`s down to just one container for the character.
2. Tweaked the styles to better represent an `x` with a circle background. I have it matching the old icon almost exactly.
3. Added `aria-label="close"` to the close button. We should actually be moving page focus back to the button that opened the modal after clicking the close button, but like you said, let's stay in the scope of this issue.

**Comment by SDavisMedia** [comment]
@samikeijonen how about giving the `<span>` a role with `role="button"`? I know that's not the preferred method over using an actual button, but I see it as the best option here. Thoughts?

**Comment by samikeijonen** [comment]
It should work but goes against good practises:) Is there a reason it can not be `<button>`?

**Comment by SDavisMedia** [comment]
@samikeijonen my fear is needing to override button styles in themes and even in some plugins. It's one of those elements that designers style heavily and with little specificity. We're almost guaranteed to end up CSS conflicts on the button for an otherwise basic looking modal.

**Comment by cklosowski** [comment]
While not perfect, I agree with @SDavisMedia here. `button` is just far too styled of an element by themes to safely use it without conflict.

But that information could serve us in the future, if we find a way to circumvent that, so thank you @samikeijonen

**Comment by SDavisMedia** [comment]
@cklosowski @samikeijonen I actually think I just got this. Here's what's going on now:

1. Added `role="button"` to the span element. That actually does make it an interactive element.
2. I give the "button" a `tabindex` so it can be navigated to once the modal is open
3. I moved the "button" position to be below the form. Note that the button was never inside of the form, but instead it's a sibling to the form. Before, it was above the form. Now it's below. When the modal opens, focus is automatically placed in the email input field. So now, you just tab through all form fields and at the very end, the close "button" is the final tab.
4. I added some JS to make the close "button" clickable via spacebar or enter key.

According to docs, this is good to go for accessibility (except maybe in some old browsers). https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_button_role But it avoids the aforementioned CSS issue and gets us probably 99% of the way there. :+1:

**Comment by SDavisMedia** [comment]
@samikeijonen everything's simpler outside of the _habits_ of WP theme developers. It's going to be an absolute support nightmare helping individual users override theme button styles. I can only assume you know how much bad, overly general CSS is out there. The only safe way to do it is with a ton of `!important` declarations. That's not about to happen.

From a web development perspective, you are correct. That's a given. With all things considered, though, this is simply one of those cases where the WordPress environment (extremely low standards for theme devs) is something we _have_ to consider.

**Pull request merged**
